name: flutter_bull
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  state_notifier: ^1.0.0
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6
  firebase_core: ^2.15.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.3
  firebase_storage: ^11.2.5
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  stack_trace: ^1.11.0
  firebase_database: ^10.2.4
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  http: ^1.1.0
  animated_list_plus: ^0.5.0
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  camera: ^0.10.5+2
  coordinated_page_route: ^0.0.3
  auto_size_text_field: ^2.2.1
  percent_indicator: ^4.2.3
  assorted_layout_widgets: ^8.0.4
  image: ^4.1.0
  dots_indicator: ^3.0.0
  jumping_dot: ^0.0.6
  zwidget: ^0.0.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  sqflite: ^2.2.8+4
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.1.0
  custom_lint: ^0.5.3
  logger: ^2.0.2+1
  build_runner: ^2.4.6
  flutter_gen_runner:

flutter:
  assets:
    - assets/images/bull-head.png
    - assets/images/bull-head-mouth-open.png
    - assets/images/bull-outline.png
    - assets/images/bull-outline-padded.png
    - assets/images/google.png
    - assets/images/at.png
    - assets/images/loading.png
    - assets/images/icons/achievements/correct.png
    - assets/images/icons/achievements/fastest.png
    - assets/images/icons/achievements/minority.png
    - assets/images/icons/achievements/f_all.png
    - assets/images/icons/achievements/f_most.png
    - assets/images/icons/achievements/f_some.png
    - assets/images/icons/achievements/cross.png
    - assets/images/icons/achievements/saboteur.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto.ttf
    - family: LapsusPro
      fonts:
        - asset: fonts/LapsusPro-Bold.otf

  uses-material-design: true
