name: flutter_bull
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  state_notifier: ^0.7.2+1
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6
  firebase_core: ^2.15.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.3
  firebase_storage: ^11.2.5
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  stack_trace: ^1.11.0
  firebase_database: ^10.2.4
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  http: ^1.1.0
  animated_list_plus: ^0.5.0
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  camera: ^0.10.5+2
  go_router: ^10.0.0
  go_router_tabs: ^0.5.0
  coordinated_page_route: ^0.0.3
  auto_size_text_field: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  sqflite: ^2.2.8+4
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  logger: ^1.4.0
  build_runner: ^2.4.6
  flutter_gen_runner:

flutter:
  assets:
    - assets/images/bull-outline.png
    - assets/images/bull-outline-padded.png
    - assets/images/google.png
    - assets/images/at.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto.ttf
    - family: LapsusPro
      fonts:
        - asset: fonts/LapsusPro-Bold.otf

  uses-material-design: true
