// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7uVj_aNpqGgWV5hJVNP1EzNwrsr2Q6mA',
    appId: '1:1088885305820:web:a274c5d79a055bb6841f19',
    messagingSenderId: '1088885305820',
    projectId: 'flutter-bull',
    authDomain: 'flutter-bull.firebaseapp.com',
    databaseURL: 'https://flutter-bull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-bull.appspot.com',
    measurementId: 'G-0WYBES14JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvojXq6Lg7kbzM6pjnB8zrfKOG8j1D8cQ',
    appId: '1:1088885305820:android:480347fea9a57a20841f19',
    messagingSenderId: '1088885305820',
    projectId: 'flutter-bull',
    databaseURL: 'https://flutter-bull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-bull.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEmUBMn1JCYCcc8AAdml7ZOZsoAGYz7qk',
    appId: '1:1088885305820:ios:8e821b89a3b56788841f19',
    messagingSenderId: '1088885305820',
    projectId: 'flutter-bull',
    databaseURL: 'https://flutter-bull-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-bull.appspot.com',
    iosClientId: '1088885305820-1r9ca6put6k47hl14s21j019vf115rlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBull',
  );
}
